[project]
name = "agent-042"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bitsandbytes>=0.49.1",
    "datasets>=4.4.2",
    "dvc[gdrive,s3,ssh]>=3.66.1",
    "fastapi>=0.128.0",
    "hf-xet>=1.2.0",
    "hydra-core>=1.3.2",
    "ipykernel>=7.1.0",
    "mlflow>=3.8.1",
    "ninja>=1.13.0",
    "numpy>=2.2.6",
    "omegaconf>=2.3.0",
    "pandas>=2.3.3",
    "peft>=0.18.1",
    "pre-commit>=4.5.1",
    "pytorch-lightning>=2.6.0",
    "ruff>=0.14.11",
    "torch>=2.9.0",
    "transformers>=4.57.3",
    "vllm>=0.13.0",

    # --- runtime deps for gateway + UI ---
    "httpx>=0.28.1",
    "pydantic-settings>=2.10.1",
    "requests>=2.32.4",
    "streamlit>=1.41.1",
    "uvicorn[standard]>=0.35.0",
]



[tool.uv.pip]
torch-backend = "auto"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["I", "E", "F"]
