"""Helpers for Airflow-managed DVC and Git sync via a disposable clone."""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

import requests

logger = logging.getLogger(__name__)

GITHUB_API_URL = "https://api.github.com"
DEFAULT_BASE_BRANCH = "develop"
DEFAULT_BOT_NAME = "agent-042-airflow-bot"
DEFAULT_BOT_EMAIL = "agent-042-airflow-bot@users.noreply.github.com"


@dataclass(frozen=True)
class GitHubRepo:
    """Parsed GitHub repository reference."""

    owner: str
    name: str

    @property
    def slug(self) -> str:
        return f"{self.owner}/{self.name}"

    @classmethod
    def from_slug(cls, slug: str) -> "GitHubRepo":
        parts = [part for part in slug.strip().split("/") if part]
        if len(parts) != 2:
            raise ValueError(f"GITHUB_REPOSITORY must be in '<owner>/<repo>' format; got {slug!r}")
        return cls(owner=parts[0], name=parts[1])


@dataclass(frozen=True)
class DvcTrackedPaths:
    """Tracked files that `dvc add` updates for a dataset directory."""

    dataset_rel_path: Path
    pointer_rel_path: Path
    gitignore_rel_path: Path


def dvc_tracked_paths(dataset_rel_path: str | Path) -> DvcTrackedPaths:
    """Return the pointer and `.gitignore` paths generated by `dvc add`."""
    rel_path = Path(dataset_rel_path)
    if rel_path.is_absolute():
        raise ValueError(f"dataset_rel_path must be relative, got {rel_path}")

    pointer_rel_path = rel_path.with_name(f"{rel_path.name}.dvc")
    gitignore_rel_path = rel_path.parent / ".gitignore"
    return DvcTrackedPaths(
        dataset_rel_path=rel_path,
        pointer_rel_path=pointer_rel_path,
        gitignore_rel_path=gitignore_rel_path,
    )


def build_github_remote_url(repo: GitHubRepo, token: str) -> str:
    """Build an authenticated HTTPS remote URL for GitHub."""
    if not token:
        raise ValueError("GitHub token must not be empty")
    return f"https://x-access-token:{quote(token, safe='')}@github.com/{repo.slug}.git"


def _link_or_copy_file(source_path: str | Path, destination_path: str | Path) -> Path:
    """Stage a file cheaply when possible, falling back to a regular copy."""
    source = Path(source_path)
    destination = Path(destination_path)

    try:
        os.link(source, destination)
    except OSError:
        shutil.copy2(source, destination)

    return destination


def stage_dataset_path(
    *, clone_root: Path, dataset_rel_path: str | Path, source_path: Path
) -> Path:
    """Replace the dataset path inside the clone with a real staged copy."""
    tracked = dvc_tracked_paths(dataset_rel_path)
    destination = clone_root / tracked.dataset_rel_path
    destination.parent.mkdir(parents=True, exist_ok=True)

    if destination.is_symlink() or destination.is_file():
        destination.unlink()
    elif destination.exists():
        shutil.rmtree(destination)

    if source_path.is_dir():
        shutil.copytree(source_path, destination, copy_function=_link_or_copy_file)
    else:
        _link_or_copy_file(source_path, destination)

    return destination


def sync_dvc_dataset_via_temp_clone(
    *,
    repo_root: Path,
    dataset_rel_path: str | Path,
    commit_message: str,
    pr_title: str,
    pr_body: str | None = None,
    source_dir: Path | None = None,
    base_branch: str = DEFAULT_BASE_BRANCH,
    bot_branch: str | None = None,
    github_repository: str | None = None,
    github_token: str | None = None,
    git_author_name: str = DEFAULT_BOT_NAME,
    git_author_email: str = DEFAULT_BOT_EMAIL,
) -> dict[str, str | bool]:
    """Run `dvc add/push` in a temp clone and sync pointer changes via GitHub."""
    _require_tool("git")
    _require_tool("dvc")

    repo_root = Path(repo_root).resolve()
    tracked = dvc_tracked_paths(dataset_rel_path)
    source_dir = (
        Path(source_dir) if source_dir is not None else repo_root / tracked.dataset_rel_path
    ).resolve()
    if not source_dir.exists():
        raise FileNotFoundError(f"Dataset source path does not exist: {source_dir}")

    local_dvc_config = repo_root / ".dvc" / "config.local"
    if not local_dvc_config.exists():
        raise FileNotFoundError(
            f"Airflow temp-clone sync requires a mounted .dvc/config.local at {local_dvc_config}"
        )

    repo = GitHubRepo.from_slug(github_repository or os.environ["GITHUB_REPOSITORY"])
    token = github_token or os.environ["GITHUB_DATA_SYNC_TOKEN"]
    remote_url = build_github_remote_url(repo, token)
    target_bot_branch = bot_branch or f"data-sync/{base_branch}"

    with tempfile.TemporaryDirectory(prefix="agent-042-sync-") as temp_dir:
        clone_dir = Path(temp_dir) / "repo"
        _run(
            [
                "git",
                "clone",
                "--depth",
                "1",
                "--branch",
                base_branch,
                remote_url,
                str(clone_dir),
            ],
            cwd=repo_root,
        )
        _prime_force_with_lease_ref(clone_dir=clone_dir, branch=target_bot_branch)

        clone_dvc_dir = clone_dir / ".dvc"
        clone_dvc_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(local_dvc_config, clone_dvc_dir / "config.local")

        stage_dataset_path(
            clone_root=clone_dir,
            dataset_rel_path=tracked.dataset_rel_path,
            source_path=source_dir,
        )

        dataset_rel_str = tracked.dataset_rel_path.as_posix()
        _run(["dvc", "add", dataset_rel_str], cwd=clone_dir)
        _run(["dvc", "push"], cwd=clone_dir)

        tracked_files = [
            tracked.pointer_rel_path.as_posix(),
            tracked.gitignore_rel_path.as_posix(),
        ]
        _run(["git", "add", "-A", "--", *tracked_files], cwd=clone_dir)

        has_changes = bool(
            _run(
                ["git", "status", "--porcelain", "--", *tracked_files],
                cwd=clone_dir,
                capture_output=True,
            ).strip()
        )
        if not has_changes:
            logger.info("No DVC pointer changes detected for %s", tracked.dataset_rel_path)
            return {
                "changed": False,
                "branch": target_bot_branch,
                "base_branch": base_branch,
                "dataset": tracked.dataset_rel_path.as_posix(),
                "repository": repo.slug,
            }

        _run(["git", "config", "user.name", git_author_name], cwd=clone_dir)
        _run(["git", "config", "user.email", git_author_email], cwd=clone_dir)
        _run(["git", "checkout", "-B", target_bot_branch], cwd=clone_dir)
        _run(["git", "commit", "-m", commit_message], cwd=clone_dir)
        _run(
            [
                "git",
                "push",
                "--force-with-lease",
                "origin",
                f"HEAD:refs/heads/{target_bot_branch}",
            ],
            cwd=clone_dir,
        )

        pr = ensure_github_pull_request(
            repo=repo,
            token=token,
            base_branch=base_branch,
            head_branch=target_bot_branch,
            title=pr_title,
            body=pr_body,
        )
        pr_url = pr.get("html_url")
        if not isinstance(pr_url, str) or not pr_url:
            raise RuntimeError("GitHub pull request response did not include a valid html_url")

        return {
            "changed": True,
            "branch": target_bot_branch,
            "base_branch": base_branch,
            "dataset": tracked.dataset_rel_path.as_posix(),
            "repository": repo.slug,
            "pr_url": pr_url,
        }


def ensure_github_pull_request(
    *,
    repo: GitHubRepo,
    token: str,
    base_branch: str,
    head_branch: str,
    title: str,
    body: str | None,
) -> dict[str, object]:
    """Ensure an open PR exists for the bot branch into the base branch."""
    headers = _github_headers(token)
    head_ref = f"{repo.owner}:{head_branch}"
    pulls_url = f"{GITHUB_API_URL}/repos/{repo.slug}/pulls"

    resp = requests.get(
        pulls_url,
        headers=headers,
        params={"state": "open", "head": head_ref, "base": base_branch},
        timeout=30,
    )
    _raise_for_status(resp, "query existing pull requests")
    pulls = resp.json()

    payload = {"title": title, "body": body or ""}
    if pulls:
        pull = pulls[0]
        update = requests.patch(
            f"{GITHUB_API_URL}/repos/{repo.slug}/pulls/{pull['number']}",
            headers=headers,
            json=payload,
            timeout=30,
        )
        _raise_for_status(update, "update pull request")
        return update.json()

    create = requests.post(
        pulls_url,
        headers=headers,
        json={
            **payload,
            "head": head_branch,
            "base": base_branch,
            "maintainer_can_modify": False,
        },
        timeout=30,
    )
    _raise_for_status(create, "create pull request")
    return create.json()


def _github_headers(token: str) -> dict[str, str]:
    return {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _require_tool(name: str) -> None:
    if shutil.which(name) is None:
        raise RuntimeError(f"Required CLI tool '{name}' is not available in PATH")


def _prime_force_with_lease_ref(*, clone_dir: Path, branch: str) -> None:
    """Fetch the remote bot branch so force-with-lease has an up-to-date lease target."""
    if not _remote_branch_exists(clone_dir=clone_dir, branch=branch):
        return

    _run(
        [
            "git",
            "fetch",
            "--depth",
            "1",
            "origin",
            f"refs/heads/{branch}:refs/remotes/origin/{branch}",
        ],
        cwd=clone_dir,
    )


def _remote_branch_exists(*, clone_dir: Path, branch: str) -> bool:
    """Return whether the remote branch already exists on origin."""
    env = os.environ.copy()
    env.setdefault("GIT_TERMINAL_PROMPT", "0")
    cmd = ["git", "ls-remote", "--exit-code", "--heads", "origin", f"refs/heads/{branch}"]
    result = subprocess.run(
        cmd,
        cwd=clone_dir,
        env=env,
        check=False,
        text=True,
        capture_output=True,
    )
    if result.returncode == 0:
        return True
    if result.returncode == 2:
        return False

    sanitized_cmd = _sanitize_cmd_for_error(cmd)
    raise RuntimeError(
        f"Command failed ({result.returncode}): {sanitized_cmd}\n"
        f"stdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )


def _sanitize_cmd_for_error(cmd: list[str]) -> str:
    sanitized_parts: list[str] = []
    prefix = "https://x-access-token:"
    suffix = "@github.com/"

    for part in cmd:
        if prefix not in part or suffix not in part:
            sanitized_parts.append(part)
            continue

        token_start = part.index(prefix) + len(prefix)
        token_end = part.index(suffix, token_start)
        sanitized_parts.append(f"{part[:token_start]}***{part[token_end:]}")

    return " ".join(sanitized_parts)


def _run(cmd: list[str], *, cwd: Path, capture_output: bool = False) -> str:
    env = os.environ.copy()
    env.setdefault("GIT_TERMINAL_PROMPT", "0")
    result = subprocess.run(
        cmd,
        cwd=cwd,
        env=env,
        check=False,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        sanitized_cmd = _sanitize_cmd_for_error(cmd)
        raise RuntimeError(
            f"Command failed ({result.returncode}): {sanitized_cmd}\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )
    if capture_output:
        return result.stdout

    if result.stdout:
        logger.info(result.stdout.strip())
    if result.stderr:
        logger.info(result.stderr.strip())
    return result.stdout


def _raise_for_status(response: requests.Response, action: str) -> None:
    try:
        response.raise_for_status()
    except requests.HTTPError as exc:
        raise RuntimeError(
            f"GitHub API failed while trying to {action}: "
            f"status={response.status_code}, body={response.text}"
        ) from exc
