"""RAG source manifest contracts and adapter-backed build pipeline."""

from rag.sources.artifacts import (
    ExtractedDocumentArtifact,
    ExtractionArtifactMeta,
    RawArtifactRef,
    extracted_artifact_from_result,
    extracted_artifact_path,
    read_extracted_artifact,
    write_extracted_artifact,
)
from rag.sources.benchmark_prep import (
    BenchmarkPrepSummary,
    benchmark_artifact_dir,
    cases_artifact_path,
    labels_artifact_path,
    metadata_artifact_path,
    prepare_benchmark_source_instance,
    read_prepared_benchmark_artifacts,
)
from rag.sources.build import (
    CatalogSourceBuildSummary,
    CatalogSourcesBuildSummary,
    GlobalSourceBuildSummary,
    SourceBuildStatus,
    SourceBuildSummary,
    build_catalog_sources,
    build_source_instance,
    build_source_instance_by_global_id,
    build_source_instances_by_global_id,
)
from rag.sources.bundles import (
    SourceChunkBundle,
    collect_source_bundles,
    collect_source_chunks,
)
from rag.sources.chunks import (
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    LLAMAINDEX_SENTENCE_SPLITTER,
    ChunkArtifact,
    ChunkingConfig,
    SourceInstanceChunkingSummary,
    chunk_artifact_path,
    chunk_extracted_artifact,
    chunk_source_instance,
    read_chunk_artifact,
    write_chunk_artifact,
)
from rag.sources.extractors import ArxivPdfExtractor, HtmlDocsExtractor, SourceExtractor
from rag.sources.fetchers import (
    ArxivPaperFetcher,
    HtmlDocsFetcher,
    SourceFetcher,
    SourceFetchResult,
)
from rag.sources.manifests import load_source_manifest
from rag.sources.models import (
    GenericSourceEntry,
    SourceManifest,
    SourceType,
    source_manifest_from_raw,
)
from rag.sources.processing import (
    SourceProcessingFailure,
    SourceProcessingSummary,
    process_source_instance,
)

__all__ = [
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "ArxivPaperFetcher",
    "ArxivPdfExtractor",
    "BenchmarkPrepSummary",
    "ChunkArtifact",
    "ChunkingConfig",
    "CatalogSourceBuildSummary",
    "CatalogSourcesBuildSummary",
    "ExtractedDocumentArtifact",
    "ExtractionArtifactMeta",
    "GenericSourceEntry",
    "GlobalSourceBuildSummary",
    "HtmlDocsFetcher",
    "HtmlDocsExtractor",
    "LLAMAINDEX_SENTENCE_SPLITTER",
    "RawArtifactRef",
    "SourceBuildStatus",
    "SourceBuildSummary",
    "SourceChunkBundle",
    "SourceExtractor",
    "SourceFetcher",
    "SourceFetchResult",
    "SourceInstanceChunkingSummary",
    "SourceManifest",
    "SourceProcessingFailure",
    "SourceProcessingSummary",
    "SourceType",
    "benchmark_artifact_dir",
    "build_catalog_sources",
    "build_source_instance",
    "build_source_instance_by_global_id",
    "build_source_instances_by_global_id",
    "cases_artifact_path",
    "chunk_artifact_path",
    "chunk_extracted_artifact",
    "chunk_source_instance",
    "collect_source_bundles",
    "collect_source_chunks",
    "extracted_artifact_from_result",
    "extracted_artifact_path",
    "labels_artifact_path",
    "load_source_manifest",
    "metadata_artifact_path",
    "prepare_benchmark_source_instance",
    "process_source_instance",
    "read_chunk_artifact",
    "read_extracted_artifact",
    "read_prepared_benchmark_artifacts",
    "source_manifest_from_raw",
    "write_extracted_artifact",
    "write_chunk_artifact",
]
