"""RAG source manifest contracts and connector registry."""

from rag.sources.artifacts import (
    ExtractedDocumentArtifact,
    ExtractionArtifactMeta,
    RawArtifactRef,
    extracted_artifact_from_result,
    extracted_artifact_path,
    read_extracted_artifact,
    write_extracted_artifact,
)
from rag.sources.build import (
    CatalogSourceBuildSummary,
    SourceBuildStatus,
    SourceBuildSummary,
    build_catalog_source,
    build_source_instance,
)
from rag.sources.bundles import SourceChunkBundle, collect_source_chunks
from rag.sources.chunks import (
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    LLAMAINDEX_SENTENCE_SPLITTER,
    ChunkArtifact,
    ChunkingConfig,
    SourceInstanceChunkingSummary,
    chunk_artifact_path,
    chunk_extracted_artifact,
    chunk_source_instance,
    read_chunk_artifact,
    write_chunk_artifact,
)
from rag.sources.connectors import (
    DEFAULT_SOURCE_CONNECTORS,
    ManifestOnlyConnector,
    SourceConnector,
    SourceConnectorRegistry,
)
from rag.sources.extractors import ArxivPdfExtractor, HtmlDocsExtractor, SourceExtractor
from rag.sources.fetchers import (
    ArxivPaperFetcher,
    HtmlDocsFetcher,
    SourceFetcher,
    SourceFetchResult,
)
from rag.sources.manifests import load_source_manifest
from rag.sources.materialize import (
    AliasPromotionResult,
    MaterializationResult,
    MaterializationSummary,
    collection_name_for_build,
    materialize_kb_collection,
    promote_materialized_alias,
    qdrant_alias_name,
    retrieval_capability_for_strategy,
    source_snapshot_id,
    validate_strategy_supported,
)
from rag.sources.models import (
    ArxivPaperEntry,
    HtmlDocsEntry,
    SourceManifest,
    SourceType,
    source_manifest_from_raw,
)
from rag.sources.processing import (
    DEFAULT_SOURCE_EXTRACTORS,
    DEFAULT_SOURCE_FETCHERS,
    SourceProcessingFailure,
    SourceProcessingSummary,
    process_source_instance,
)

__all__ = [
    "DEFAULT_SOURCE_CONNECTORS",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_SOURCE_EXTRACTORS",
    "DEFAULT_SOURCE_FETCHERS",
    "ArxivPaperEntry",
    "ArxivPaperFetcher",
    "ArxivPdfExtractor",
    "AliasPromotionResult",
    "ChunkArtifact",
    "ChunkingConfig",
    "CatalogSourceBuildSummary",
    "ExtractedDocumentArtifact",
    "ExtractionArtifactMeta",
    "HtmlDocsEntry",
    "HtmlDocsFetcher",
    "HtmlDocsExtractor",
    "LLAMAINDEX_SENTENCE_SPLITTER",
    "ManifestOnlyConnector",
    "MaterializationResult",
    "MaterializationSummary",
    "RawArtifactRef",
    "SourceBuildStatus",
    "SourceBuildSummary",
    "SourceChunkBundle",
    "SourceConnector",
    "SourceConnectorRegistry",
    "SourceExtractor",
    "SourceFetcher",
    "SourceFetchResult",
    "SourceInstanceChunkingSummary",
    "SourceManifest",
    "SourceProcessingFailure",
    "SourceProcessingSummary",
    "SourceType",
    "build_catalog_source",
    "build_source_instance",
    "chunk_artifact_path",
    "chunk_extracted_artifact",
    "chunk_source_instance",
    "collect_source_chunks",
    "collection_name_for_build",
    "extracted_artifact_from_result",
    "extracted_artifact_path",
    "load_source_manifest",
    "materialize_kb_collection",
    "promote_materialized_alias",
    "process_source_instance",
    "qdrant_alias_name",
    "read_chunk_artifact",
    "read_extracted_artifact",
    "source_manifest_from_raw",
    "source_snapshot_id",
    "retrieval_capability_for_strategy",
    "validate_strategy_supported",
    "write_extracted_artifact",
    "write_chunk_artifact",
]
